interface Plugin {
    id: string;
    name: string;
    description: string;
    icon: string;
    category: string;
  }
export const pluginStore: Plugin[] = [
  {
    id: "CoinGecko",
    name: "CoinGecko", 
    description: "Get coin information using CoinGecko API",
    icon: "🪙",
    category: "Search",
  },
  {
    id: "X-analyst",
    name: "X Analyst", 
    description: "Get market analysis via x.com data",
    icon: "𝕏",
    category: "Search",
  },
  {
    id: "sendETH",
    name: "Send ETH", 
    description: "Send ETH to a wallet",
    icon: "💰",
    category: "Transaction",
  },
  {
    id: "Cross-Chain-Swap",
    name: "Cross-Chain Swap",
    description: "Swap token Cross chain using near intent.",
    icon: "❶",
    category: "Transaction",
  },
  {
    id: "birdeye",
    name: "Birdeye",
    description: "Get information about a wallet/token using the Birdeye API.",
    icon: "🐦",
    category: "Analytics",
  },
  {
    id: "coinMarketCap",
    name: "CoinMarketCap",
    description: "Get information about a token using the CoinMarketCap API.",
    icon: "🪙",
    category: "Analytics",
  },
  {
    id: "polymarket",
    name: "Polymarket",
    description: "Bet on Polymarket",
    icon: "📈",
    category: "Betting",
  },
  {
    id: "dexscreener",
    name: "Dexscreener",
    description: "Get information about a token using the Dexscreener API.",
    icon: "🔄",
    category: "Analytics",
  },
  {
    id: "allora",
    name: "Allora",
    description: "Get price predictions using Allora API",
    icon: "🔮",
    category: "Analytics",
  },
  {
    id: "zeroEx",
    name: "ZeroEx",
    description: "Get quotes and swap on 0x",
    icon: "🔄",
    category: "Transaction",
  },
  {
    id: "avnu",
    name: "Avnu",
    description: "Swap tokens on Starknet",
    icon: "💱",
    category: "Transaction",
  },
  {
    id: "balancer",
    name: "Balancer",
    description: "Swap tokens and provide liquidity on Balancer",
    icon: "⚖️",
    category: "Transaction",
  },
  {
    id: "balmy",
    name: "Balmy",
    description: "Swap tokens on Balmy",
    icon: "🔄",
    category: "Transaction",
  },
  {
    id: "cosmosbank",
    name: "Cosmosbank",
    description: "Interact with Cosmos tokens",
    icon: "🌌",
    category: "Transaction",
  },
  {
    id: "crossmintHeadless",
    name: "Crossmint Headless Checkout",
    description: "Purchase any NFT on any chain using Crossmint",
    icon: "🛒",
    category: "NFT",
  },
  {
    id: "crossmintMint",
    name: "Crossmint Mint",
    description: "Create a wallet, mint tokens and get test tokens on any chain using Crossmint",
    icon: "🏭",
    category: "Transaction",
  },
  {
    id: "debridge",
    name: "DeBridge",
    description: "Bridge tokens on DeBridge",
    icon: "🌉",
    category: "Transaction",
  },
  {
    id: "erc20",
    name: "ERC20",
    description: "Interact with any ERC20 token",
    icon: "💎",
    category: "Token",
  },
  {
    id: "erc721",
    name: "ERC721",
    description: "Interact with any ERC721 token",
    icon: "🎨",
    category: "NFT",
  },
  {
    id: "etherscan",
    name: "Etherscan",
    description: "Get transaction information using Etherscan API",
    icon: "🔍",
    category: "Analytics",
  },
  {
    id: "farcaster",
    name: "Farcaster",
    description: "Read and post casts on Farcaster",
    icon: "📡",
    category: "Social",
  },
  {
    id: "ionic",
    name: "Ionic",
    description: "Borrow and lend on Ionic",
    icon: "🏦",
    category: "DeFi",
  },
  {
    id: "ironclad",
    name: "Ironclad",
    description: "Create positions on Ironclad",
    icon: "🛡️",
    category: "DeFi",
  },
  {
    id: "jsonRpc",
    name: "JSON RPC",
    description: "Call any JSON RPC endpoint",
    icon: "🔌",
    category: "Developer",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    description: "Swap tokens on Jupiter",
    icon: "🌍",
    category: "Transaction",
  },
  {
    id: "kim",
    name: "KIM",
    description: "Swap tokens on KIM",
    icon: "💱",
    category: "Transaction",
  },
  {
    id: "lulo",
    name: "Lulo",
    description: "Deposit USDC on Lulo",
    icon: "💵",
    category: "DeFi",
  },
  {
    id: "meteora",
    name: "Meteora",
    description: "Create liquidity pools on Meteora",
    icon: "🌠",
    category: "DeFi",
  },
  {
    id: "modeGovernance",
    name: "Mode Governance",
    description: "Create a governance proposal on Mode",
    icon: "📜",
    category: "Governance",
  },
  {
    id: "modeVoting",
    name: "Mode Voting",
    description: "Vote on a governance proposal on Mode",
    icon: "🗳️",
    category: "Governance",
  },
  {
    id: "modeSpray",
    name: "Mode Spray",
    description: "Spray tokens on Mode",
    icon: "💨",
    category: "Transaction",
  },
  {
    id: "nansen",
    name: "Nansen",
    description: "Get Nansen information using Nansen API",
    icon: "📊",
    category: "Analytics",
  },
  {
    id: "opensea",
    name: "OpenSea",
    description: "Get nft and sales information using OpenSea API",
    icon: "🌊",
    category: "NFT",
  },
  {
    id: "orca",
    name: "Orca",
    description: "Create positions on Orca",
    icon: "🐋",
    category: "DeFi",
  },
  {
    id: "plunderSwap",
    name: "PlunderSwap",
    description: "Currency exchange on Zilliqa",
    icon: "⚔️",
    category: "Transaction",
  }
];